### PR TITLE
bumping to latest versions of codemirror

### PR DESCRIPTION
**Pull request by utkukaratas**

### CODE REVIEW

**Comment by utkukaratas** [comment]
@Sodik i think this will fix MC syntax highlighting. i had declared some strict equal package versions. with this pr we switch to compatible versioning.

**Review by Sodik — APPROVED** [review]

**Comment by utkukaratas** [comment]
verify

**Comment by utkukaratas** [comment]
verify

**Comment by utkukaratas** [comment]
verify

**Pull request closed without merging**
